# Example Site settings

# google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - blog.md
  # - project.md
  - about.md

footer: 'follow me on <a href="https://www.instagram.com/kyrllzh/">instagram</a>'

style: dark # dark (default) or light
listen_for_clients_preferred_style: false # true or false (default)

plugins:
  - jekyll-seo-tag
